"""RPMI-CMV deterministic Python V0 scaffold."""

from rpmi.config import (
    AlgorithmConfig,
    DemandWeightConfig,
    FeatureFlags,
    RunConfig,
    SimConfig,
    config_to_canonical_dict,
    config_to_snapshot_dict,
    hash_config,
    load_config,
    validate_v0_flags,
)
from rpmi.run import RunArtifacts, init_run
from rpmi.dynamics import (
    clip_accel_for_kinematics,
    combine_nominal_and_action,
    compute_gap_margin,
    compute_idm_accel,
    compute_nominal_accel,
    detect_hard_brake,
    detect_overlap,
    find_leader,
    occupied_interval,
    sort_lane_vehicles,
    step_traffic,
    step_vehicle_kinematic,
)
from rpmi.logging_schema import append_realized_event_rows, append_vehicle_step_rows
from rpmi.slots import (
    Edge,
    EdgeQuality,
    IntervalResult,
    Slot,
    SlotInventoryParams,
    build_edges,
    compute_edge_qualities,
    compute_edge_validity,
    compute_feasible_interval,
    compute_inventory_metrics,
    compute_recovery_debt,
    compute_safety_distances,
    edge_quality_to_row,
    evaluate_reachability,
    evaluate_safety,
    evaluate_survival,
    generate_slots,
    generate_time_grid,
    get_target_lane_pairs,
    make_edge_id,
    make_slot_id,
    slot_to_row,
)
from rpmi.state import RoadConfig, TrafficState, VehicleState, hash_state

__all__ = [
    "AlgorithmConfig",
    "DemandWeightConfig",
    "Edge",
    "EdgeQuality",
    "FeatureFlags",
    "IntervalResult",
    "RunArtifacts",
    "RunConfig",
    "RoadConfig",
    "SimConfig",
    "Slot",
    "SlotInventoryParams",
    "TrafficState",
    "VehicleState",
    "append_realized_event_rows",
    "append_vehicle_step_rows",
    "build_edges",
    "clip_accel_for_kinematics",
    "combine_nominal_and_action",
    "config_to_canonical_dict",
    "config_to_snapshot_dict",
    "compute_edge_qualities",
    "compute_edge_validity",
    "compute_feasible_interval",
    "compute_gap_margin",
    "compute_idm_accel",
    "compute_inventory_metrics",
    "compute_nominal_accel",
    "compute_recovery_debt",
    "compute_safety_distances",
    "detect_hard_brake",
    "detect_overlap",
    "edge_quality_to_row",
    "evaluate_reachability",
    "evaluate_safety",
    "evaluate_survival",
    "find_leader",
    "generate_slots",
    "generate_time_grid",
    "get_target_lane_pairs",
    "hash_config",
    "hash_state",
    "init_run",
    "load_config",
    "make_edge_id",
    "make_slot_id",
    "occupied_interval",
    "sort_lane_vehicles",
    "slot_to_row",
    "step_traffic",
    "step_vehicle_kinematic",
    "validate_v0_flags",
]

__version__ = "0.1.0"
